version: "3.8"

services:
  app:
    image: lazarh/better-cups:latest
    networks:
      - host
    secrets:
      - source: cups_pass
        target: cups_pass
    volumes:
      - cups-config:/etc/cups
      - cups-spool:/var/spool/cups
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first

secrets:
  cups_pass:
    external: true

volumes:
  cups-config:
  cups-spool:

networks:
  host:
    external: true
    name: host
