version: "3.8"

services:
  app:
    image: lazarh/better-cups:latest
    network_mode: host
    environment:
      - CUPS_PASSWORD=changeme
      - CUPS_ALLOW_CIDR=192.168.0.0/16
    volumes:
      - cups-config:/etc/cups
      - cups-spool:/var/spool/cups
    restart: unless-stopped

volumes:
  cups-config:
  cups-spool:
